### ISSUE TITLE
Doesn't work with datetime.now() calls with an argument (timezone)

### ISSUE THREAD

**Issue by Deimos** [pokidovea/immobilus#1]
The `datetime.now()` calls in my code use the `tz` argument with the `timezone` class added in Python 3.2, similar to:

```
from datetime import datetime, timezone

now = datetime.now(timezone.utc)
```

Immobilus isn't able to work with these, since it overrides `now()` with a function that doesn't take any arguments.

**Comment by pokidovea** [comment]
Please check with 0.2.1 version

**Comment by Deimos** [comment]
The code seems to be broken right now still:

```
if tz:
>           _datetime = tz.localize(_datetime)
E           AttributeError: 'datetime.timezone' object has no attribute 'localize'
```

**Comment by pokidovea** [comment]
Try now, please

**Comment by Deimos** [comment]
Seems to be working fine now, thanks for the updates.
