### ISSUE TITLE
UnicodeDecodeError on installing with C locale

### ISSUE THREAD

**Issue by islamgulov** [pokidovea/immobilus#29]
UnicodeDecodeError when installing immobilus using pip module when the locale is set to C (for example on installing using ansible pip module).

`LC_ALL=C pip install -r ./requirements.txt`
 Results:
```
Collecting immobilus==1.4.0 (from -r ./requirements.txt (line 45))
  Using cached immobilus-1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-v8ng1rqn/immobilus/setup.py", line 6, in <module>
        long_description = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6766: ordinal not in range(128)
 
```

This is probably related to having non-ascii character in contributes name from README.rst

--
If anyone else runs into the same error, explicitly set locale in your ansible task
```
  environment:
    LC_ALL: en_US.UTF-8 
```

**Comment by pokidovea** [comment]
Thanks, I'll investigate.

**Comment by pokidovea** [comment]
Fixed, see https://pypi.python.org/pypi/immobilus/1.4.1
