### ISSUE TITLE
Timezone aware

### ISSUE THREAD

**Issue by azmeuk** [pokidovea/immobilus#3]
Hi. It would be great if immobilus had a `tz_offset` parameter, like the freezegun one, so for instance `datetime.now` and `datetime.utcnow` could return different values.

**Comment by pokidovea** [comment]
Thanks for issue. I'll make it asap.

**Comment by pokidovea** [comment]
Please, check in master, then I'll create a new version for pypi

**Comment by azmeuk** [comment]
Just checked, it seems great!

**Comment by pokidovea** [comment]
Version 0.2.7 is ready. Thanks!
