### ISSUE TITLE
immobilus is incompatible with logging.Formatter()

### ISSUE THREAD

**Issue by imankulov** [pokidovea/immobilus#30]
Hi @pokidovea! Just found one issue of using immobilius fake functions as class attributes, in particular in the logging.Formatter class.

## Issue

The stdlib formatter contains following code

```python
class Formatter(object):
    converter = time.localtime
```

The converter is called to convert log record timestamp to ASCII string. The problem is, `time.localtime` (which has type "builtin_function_or_method") and `fake_localtime` (which has type "function") behave differently as class attributes: the latter is bound with a parent class instance on initialization.

## Case without patching

```python
# Python 3.6.2 (default, Aug  2 2017, 15:33:18)
>>> import logging
>>> logging.Formatter('%(asctime)s').format(logging.makeLogRecord({}))
'2018-06-22 18:19:20,435'
>>> logging.Formatter.converter
<built-in function localtime>
>>> logging.Formatter().converter
<built-in function localtime>
```

## Case with patching

```python
# Python 3.6.2 (default, Aug  2 2017, 15:33:18)
>>> from immobilus import immobilus
>>> import logging
>>> logging.Formatter('%(asctime)s').format(logging.makeLogRecord({}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/roman/.pyenv/versions/3.6.2/lib/python3.6/logging/__init__.py", line 577, in format
    record.asctime = self.formatTime(record, self.datefmt)
  File "/Users/roman/.pyenv/versions/3.6.2/lib/python3.6/logging/__init__.py", line 513, in formatTime
    ct = self.converter(record.created)
TypeError: fake_localtime() takes from 0 to 1 positional arguments but 2 were given
>>> logging.Formatter.converter
<function fake_localtime at 0x10ebe3950>
>>> logging.Formatter().converter
<bound method fake_localtime of <logging.Formatter object at 0x10e9ccac8>>
```

## Workaround

For myself I found a workaround which kind of works, but solves only this specific case

```python
>>> from immobilus import immobilus
>>> import logging
>>> logging.Formatter.converter = staticmethod(logging.Formatter.converter)
>>> logging.Formatter('%(asctime)s').format(logging.makeLogRecord({}))
'2018-06-22 18:20:46,534'
```

## Proper solution

Probably, the only generalized solution is to turn fake_localtime to an object with a `__get__` method, always returning itself (disallowing binding), but I haven't experimented with this.

**Comment by pokidovea** [comment]
Please, look at #31 .

**Comment by pokidovea** [comment]
https://pypi.org/project/immobilus/1.4.2/

**Comment by imankulov** [comment]
@pokidovea, thanks a lot for your fix. Works like a charm ✨
