### ISSUE TITLE
Unexpected behavior with time.time

### ISSUE THREAD

**Issue by azmeuk** [pokidovea/immobilus#4]
My system is GMT+2, and it seems `time.time` returns local time when I think it should return UTC time.
```python
with immobilus.immobilus("1970-01-01 00:00:00"):
    print(time.time())

# -3600.0 is printed
# 0.0 is expected
```
What do you think?

**Comment by pokidovea** [comment]
Yep, it was a bug in datetime_to_timestamp function. Check please.

**Comment by azmeuk** [comment]
It seems to be good. Thank you!

**Comment by azmeuk** [comment]
Actually I am reopening the issue because now `time.time` returns an `int` where it should return a `float`.

**Comment by pokidovea** [comment]
Merged
